name = "sg2" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg2.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg2.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "cache.netflix.com.sg2.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "graph.instagram.com.sg2.afrcloud.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.sg2.afrcloud.xyz"
custom_domain = true

[vars]
# UUID = "2aeee1cd-954a-4f69-b2c0-2de59511707b"
# PROXYIP = "138.2.104.102"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "2aeee1cd-954a-4f69-b2c0-2de59511707b"
proxyip = "138.2.104.102"